# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'postInstallComponentDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(570, 464)
        self.instructionsFooterLabel = QtWidgets.QLabel(Dialog)
        self.instructionsFooterLabel.setGeometry(QtCore.QRect(30, 280, 511, 61))
        self.instructionsFooterLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.instructionsFooterLabel.setWordWrap(True)
        self.instructionsFooterLabel.setObjectName("instructionsFooterLabel")
        self.logoLabel = QtWidgets.QLabel(Dialog)
        self.logoLabel.setGeometry(QtCore.QRect(420, 30, 131, 51))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("../images/GWA_logo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.topLabel = QtWidgets.QLabel(Dialog)
        self.topLabel.setGeometry(QtCore.QRect(20, 70, 401, 41))
        self.topLabel.setWordWrap(True)
        self.topLabel.setObjectName("topLabel")
        self.instructionsMainLabel = QtWidgets.QLabel(Dialog)
        self.instructionsMainLabel.setGeometry(QtCore.QRect(30, 180, 511, 61))
        self.instructionsMainLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.instructionsMainLabel.setWordWrap(True)
        self.instructionsMainLabel.setObjectName("instructionsMainLabel")
        self.bottomLabel = QtWidgets.QLabel(Dialog)
        self.bottomLabel.setGeometry(QtCore.QRect(20, 380, 511, 31))
        self.bottomLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.bottomLabel.setWordWrap(True)
        self.bottomLabel.setObjectName("bottomLabel")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(470, 420, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.instructionsHeaderLabel = QtWidgets.QLabel(Dialog)
        self.instructionsHeaderLabel.setGeometry(QtCore.QRect(20, 150, 101, 41))
        self.instructionsHeaderLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.instructionsHeaderLabel.setWordWrap(True)
        self.instructionsHeaderLabel.setObjectName("instructionsHeaderLabel")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(20, 140, 531, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dirSelectionButton = QtWidgets.QPushButton(Dialog)
        self.dirSelectionButton.setGeometry(QtCore.QRect(524, 250, 21, 23))
        self.dirSelectionButton.setObjectName("dirSelectionButton")
        self.continueButton = QtWidgets.QPushButton(Dialog)
        self.continueButton.setGeometry(QtCore.QRect(290, 420, 75, 23))
        self.continueButton.setObjectName("continueButton")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(20, 320, 531, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.dirPathText = QtWidgets.QPlainTextEdit(Dialog)
        self.dirPathText.setGeometry(QtCore.QRect(30, 250, 471, 24))
        self.dirPathText.setObjectName("dirPathText")
        self.componentLogoLabel = QtWidgets.QLabel(Dialog)
        self.componentLogoLabel.setGeometry(QtCore.QRect(420, 90, 131, 51))
        self.componentLogoLabel.setText("")
        self.componentLogoLabel.setPixmap(QtGui.QPixmap("../images/beamLogo.png"))
        self.componentLogoLabel.setScaledContents(False)
        self.componentLogoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.componentLogoLabel.setObjectName("componentLogoLabel")
        self.skipButton = QtWidgets.QPushButton(Dialog)
        self.skipButton.setGeometry(QtCore.QRect(380, 420, 75, 23))
        self.skipButton.setObjectName("skipButton")
        self.bottomLabel1 = QtWidgets.QLabel(Dialog)
        self.bottomLabel1.setGeometry(QtCore.QRect(20, 340, 511, 31))
        self.bottomLabel1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.bottomLabel1.setWordWrap(True)
        self.bottomLabel1.setObjectName("bottomLabel1")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "GWA Toolbox Installation"))
        self.instructionsFooterLabel.setText(_translate("Dialog", "Afterwards click \"Continue\"."))
        self.topLabel.setText(_translate("Dialog", "BEAM is a software for analysing optical and thermal data derived with satellites operated by Europen Space Agency (ESA) and other organisation."))
        self.instructionsMainLabel.setText(_translate("Dialog", "The GWA Toolbox installer will now perform additional post installation tasks for BEAM. If you changed the BEAM installation directory during the previous step, make sure that you update the path to the directory below."))
        self.bottomLabel.setText(_translate("Dialog", "If you would like to abandon the installation altogether, click \"Cancel\". The GWA Toolbox components that were already installed will remain on your computer."))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.instructionsHeaderLabel.setText(_translate("Dialog", "Instructions:"))
        self.dirSelectionButton.setText(_translate("Dialog", "..."))
        self.continueButton.setText(_translate("Dialog", "Continue"))
        self.dirPathText.setPlainText(_translate("Dialog", "dfgdgfdgf"))
        self.skipButton.setText(_translate("Dialog", "Skip"))
        self.bottomLabel1.setText(_translate("Dialog", "If you do not want to install this GWA Toolbox component click \"Skip\" to go the installation of the next component. However, note that by doing so you will not get the full GWA Toolbox functionality."))

